# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\git\MAC_SN Burning\BurnMAC.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(631, 381)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(631, 381))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_8.addWidget(self.label)
        self.comboBox_proMode = QtWidgets.QComboBox(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.comboBox_proMode.setFont(font)
        self.comboBox_proMode.setObjectName("comboBox_proMode")
        self.comboBox_proMode.addItem("")
        self.comboBox_proMode.addItem("")
        self.comboBox_proMode.addItem("")
        self.horizontalLayout_8.addWidget(self.comboBox_proMode)
        self.label_9 = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        self.lineEdit_comPort = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_comPort.setEnabled(False)
        self.lineEdit_comPort.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit_comPort.setFont(font)
        self.lineEdit_comPort.setText("")
        self.lineEdit_comPort.setReadOnly(False)
        self.lineEdit_comPort.setObjectName("lineEdit_comPort")
        self.horizontalLayout_8.addWidget(self.lineEdit_comPort)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_9.addWidget(self.label_2)
        self.lineEdit_ipAddr = QtWidgets.QLineEdit(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit_ipAddr.setFont(font)
        self.lineEdit_ipAddr.setText("")
        self.lineEdit_ipAddr.setReadOnly(False)
        self.lineEdit_ipAddr.setObjectName("lineEdit_ipAddr")
        self.horizontalLayout_9.addWidget(self.lineEdit_ipAddr)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.lineEdit_macStart = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_macStart.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit_macStart.setFont(font)
        self.lineEdit_macStart.setText("")
        self.lineEdit_macStart.setReadOnly(False)
        self.lineEdit_macStart.setObjectName("lineEdit_macStart")
        self.horizontalLayout_7.addWidget(self.lineEdit_macStart)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.lineEdit_macEnd = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_macEnd.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit_macEnd.setFont(font)
        self.lineEdit_macEnd.setText("")
        self.lineEdit_macEnd.setReadOnly(False)
        self.lineEdit_macEnd.setObjectName("lineEdit_macEnd")
        self.horizontalLayout_6.addWidget(self.lineEdit_macEnd)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checkBox_MAC = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_MAC.setText("")
        self.checkBox_MAC.setObjectName("checkBox_MAC")
        self.horizontalLayout_5.addWidget(self.checkBox_MAC)
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.lineEdit_macInterval = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_macInterval.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit_macInterval.setFont(font)
        self.lineEdit_macInterval.setText("")
        self.lineEdit_macInterval.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_macInterval.setReadOnly(False)
        self.lineEdit_macInterval.setObjectName("lineEdit_macInterval")
        self.horizontalLayout_5.addWidget(self.lineEdit_macInterval)
        spacerItem4 = QtWidgets.QSpacerItem(400, 24, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_8 = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.lineEdit_SNStart = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_SNStart.setEnabled(False)
        self.lineEdit_SNStart.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit_SNStart.setFont(font)
        self.lineEdit_SNStart.setText("")
        self.lineEdit_SNStart.setReadOnly(False)
        self.lineEdit_SNStart.setObjectName("lineEdit_SNStart")
        self.horizontalLayout.addWidget(self.lineEdit_SNStart)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.lineEdit_SNEnd = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_SNEnd.setEnabled(False)
        self.lineEdit_SNEnd.setMinimumSize(QtCore.QSize(180, 27))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit_SNEnd.setFont(font)
        self.lineEdit_SNEnd.setText("")
        self.lineEdit_SNEnd.setReadOnly(False)
        self.lineEdit_SNEnd.setObjectName("lineEdit_SNEnd")
        self.horizontalLayout_2.addWidget(self.lineEdit_SNEnd)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox_SN = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_SN.setText("")
        self.checkBox_SN.setObjectName("checkBox_SN")
        self.horizontalLayout_3.addWidget(self.checkBox_SN)
        self.label_7 = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.lineEdit_SNInterval = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_SNInterval.setEnabled(False)
        self.lineEdit_SNInterval.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_SNInterval.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit_SNInterval.setFont(font)
        self.lineEdit_SNInterval.setText("")
        self.lineEdit_SNInterval.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_SNInterval.setReadOnly(False)
        self.lineEdit_SNInterval.setObjectName("lineEdit_SNInterval")
        self.horizontalLayout_3.addWidget(self.lineEdit_SNInterval)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.label_12 = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_3.addWidget(self.label_12)
        self.lineEdit_SNPref = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_SNPref.setEnabled(False)
        self.lineEdit_SNPref.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit_SNPref.setFont(font)
        self.lineEdit_SNPref.setText("")
        self.lineEdit_SNPref.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_SNPref.setReadOnly(False)
        self.lineEdit_SNPref.setObjectName("lineEdit_SNPref")
        self.horizontalLayout_3.addWidget(self.lineEdit_SNPref)
        spacerItem8 = QtWidgets.QSpacerItem(31, 24, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 40))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.radioButton_singal = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.radioButton_singal.setFont(font)
        self.radioButton_singal.setObjectName("radioButton_singal")
        self.horizontalLayout_10.addWidget(self.radioButton_singal)
        self.radioButton_continuous = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.radioButton_continuous.setFont(font)
        self.radioButton_continuous.setObjectName("radioButton_continuous")
        self.horizontalLayout_10.addWidget(self.radioButton_continuous)
        self.radioButton_manual = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.radioButton_manual.setFont(font)
        self.radioButton_manual.setObjectName("radioButton_manual")
        self.horizontalLayout_10.addWidget(self.radioButton_manual)
        self.horizontalLayout_11.addWidget(self.groupBox)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem9)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_modify = QtWidgets.QPushButton(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.pushButton_modify.setFont(font)
        self.pushButton_modify.setObjectName("pushButton_modify")
        self.horizontalLayout_4.addWidget(self.pushButton_modify)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem10)
        self.pushButton_start = QtWidgets.QPushButton(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setObjectName("pushButton_start")
        self.horizontalLayout_4.addWidget(self.pushButton_start)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem11)
        self.pushButton_stop = QtWidgets.QPushButton(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.pushButton_stop.setFont(font)
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.horizontalLayout_4.addWidget(self.pushButton_stop)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem12)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_14.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_11 = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_13.addWidget(self.label_11)
        self.lineEdit_macCurrent = QtWidgets.QLineEdit(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit_macCurrent.setFont(font)
        self.lineEdit_macCurrent.setText("")
        self.lineEdit_macCurrent.setReadOnly(True)
        self.lineEdit_macCurrent.setObjectName("lineEdit_macCurrent")
        self.horizontalLayout_13.addWidget(self.lineEdit_macCurrent)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem13)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_10 = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_12.addWidget(self.label_10)
        self.lineEdit_SNCurrent = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_SNCurrent.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit_SNCurrent.setFont(font)
        self.lineEdit_SNCurrent.setText("")
        self.lineEdit_SNCurrent.setReadOnly(True)
        self.lineEdit_SNCurrent.setObjectName("lineEdit_SNCurrent")
        self.horizontalLayout_12.addWidget(self.lineEdit_SNCurrent)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem14)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralWidget)
        self.textBrowser.setMinimumSize(QtCore.QSize(300, 0))
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_2.addWidget(self.textBrowser)
        self.horizontalLayout_14.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout_14, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "烧写方式"))
        self.comboBox_proMode.setItemText(0, _translate("MainWindow", "SSH"))
        self.comboBox_proMode.setItemText(1, _translate("MainWindow", "Telnet"))
        self.comboBox_proMode.setItemText(2, _translate("MainWindow", "Serial"))
        self.label_9.setText(_translate("MainWindow", "COM"))
        self.label_2.setText(_translate("MainWindow", "IP地址"))
        self.label_3.setText(_translate("MainWindow", "MAC起始地址"))
        self.label_4.setText(_translate("MainWindow", "MAC终止地址"))
        self.label_5.setText(_translate("MainWindow", "地址间隔"))
        self.label_8.setText(_translate("MainWindow", "SN起始地址"))
        self.label_6.setText(_translate("MainWindow", "SN终止地址"))
        self.label_7.setText(_translate("MainWindow", "地址间隔"))
        self.label_12.setText(_translate("MainWindow", "SN前缀"))
        self.radioButton_singal.setText(_translate("MainWindow", "单次烧写"))
        self.radioButton_continuous.setText(_translate("MainWindow", "连续烧写"))
        self.radioButton_manual.setText(_translate("MainWindow", "手动烧写"))
        self.pushButton_modify.setText(_translate("MainWindow", "编辑"))
        self.pushButton_start.setText(_translate("MainWindow", "开始"))
        self.pushButton_stop.setText(_translate("MainWindow", "停止"))
        self.label_11.setText(_translate("MainWindow", "烧写MAC"))
        self.label_10.setText(_translate("MainWindow", "烧写SN"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

